<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AeterniUI.Icons.FontAwesome</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AeterniUI\AeterniUI.csproj" />
    <None Include="THIRD-PARTY-NOTICES.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
