using AeterniUI.Attributes;
using AeterniUI.Modules;
using AeterniUI.Services;
using AeterniUI.Services.Impl;
using Microsoft.AspNetCore.Components;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.JSInterop;

namespace AeterniUI.Components;

public class AeterniComponent : ComponentBase, IAsyncDisposable
{
    [Inject] protected IServiceProvider ServiceProvider { get; set; } = default!;

    private JsModuleManager? _jsModuleManager;
    private IReadOnlyList<JsModuleAttribute>? _jsModules;
    private bool _jsScanned;
    private bool _jsModuleLoaded;
    private DotNetObjectReference<AeterniComponent>? _dotNetReference;

    #region 私有字段

    private readonly string _instanceId = $"aeterni-{Guid.NewGuid():N}";
    private AeterniUITextOptions? _uiText;
    private bool _disposed;
    private ElementReference _rootElement;
    private bool _rootElementInitialized;
    private bool _rootElementChanged;
    private bool _externalElementProvided;
    #endregion

    #region 组件参数

    [Parameter]
    public string? Id { get; set; }

    [Parameter]
    public bool Disabled { get; set; }

    [Parameter]
    public bool Visible { get; set; } = true;

    [Parameter]
    public string? Class { get; set; }

    [Parameter]
    public string? Style { get; set; }

    [Parameter]
    public ElementReference? Element { get; set; }

    [Parameter(CaptureUnmatchedValues = true)]
    public IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

    [Parameter]
    public EventCallback<ElementReference> ElementChanged { get; set; }

    #endregion

    /// <summary>
    /// Resolves the JS module manager only for components that declare a
    /// <see cref="JsModuleAttribute"/>. Components without JS modules do not
    /// require JS initialization work.
    /// </summary>
    protected JsModuleManager JsModuleManager =>
        _jsModuleManager ??= ServiceProvider.GetRequiredService<JsModuleManager>();

    /// <summary>
    /// Gets the localisable text table. Falls back to the built-in defaults when
    /// the host did not register <see cref="AeterniUIOptions"/>.
    /// </summary>
    protected AeterniUITextOptions UiText =>
        _uiText ??= ServiceProvider.GetService<AeterniUIOptions>()?.Text ?? new AeterniUITextOptions();

    /// <summary>
    /// Gets the modules declared by the concrete component, including inherited declarations.
    /// </summary>
    protected IReadOnlyList<JsModuleAttribute> JsModules =>
        _jsModules ??= JsComponentMetadataCache.Get(GetType()).Modules;

    /// <summary>
    /// Indicates whether the component has opted into the JS module lifecycle.
    /// </summary>
    protected bool HasJsModules => JsModules.Count > 0;

    /// <summary>
    /// Gets the stable identifier for this component instance. This value is
    /// generated by the base class and is suitable for JS module instance keys.
    /// </summary>
    public string InstanceId => _instanceId;

    /// <summary>
    /// Gets the identifier that should be rendered on the component's root element.
    /// </summary>
    public string ElementId => string.IsNullOrWhiteSpace(Id) ? InstanceId : Id.Trim();

    /// <summary>
    /// Compatibility alias for <see cref="InstanceId"/>.
    /// </summary>
    public string ComponentId => InstanceId;

    public ElementReference RootElement
    {
        get => _rootElement;
        protected set
        {
            if (string.IsNullOrEmpty(value.Id))
            {
                ClearRootElement();
                return;
            }

            SetRootElement(value);
        }
    }

    protected bool RootElementInitialized => _rootElementInitialized;

    /// <summary>
    /// Indicates whether the component should emit disabled semantics when
    /// <see cref="Disabled"/> is true.
    /// </summary>
    protected virtual bool SupportsDisabled => false;

    /// <summary>
    /// Creates a class builder for composing the component's base, state and consumer classes.
    /// </summary>
    protected static ClassBuilder ClassBuilder(params string?[] classes) => new(classes);

    /// <summary>
    /// Creates a style builder for composing the component's inline style declarations.
    /// </summary>
    protected static StyleBuilder StyleBuilder(params string?[] styles) => new(styles);

    /// <summary>
    /// Creates the class builder initialized with the consumer-provided class attribute.
    /// </summary>
    protected virtual ClassBuilder BuildClass() => ClassBuilder(Class);

    /// <summary>
    /// Creates the style builder initialized with the consumer-provided style attribute.
    /// </summary>
    protected virtual StyleBuilder BuildStyle() => StyleBuilder(Style);

    /// <summary>
    /// Returns the unmatched attributes supplied by the consumer.
    /// The returned collection also contains the normalized root element id,
    /// class, style and supported state attributes. Components should pass this
    /// collection to <c>@attributes</c> instead of rendering those attributes twice.
    /// </summary>
    protected virtual IReadOnlyDictionary<string, object> BuildAttributes()
    {
        var attributes = new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase);
        if (AdditionalAttributes is not null)
        {
            foreach (var attribute in AdditionalAttributes)
            {
                attributes[attribute.Key] = attribute.Value;
            }
        }

        attributes["id"] = ElementId;

        var className = BuildClass().Build();
        if (!string.IsNullOrWhiteSpace(className))
        {
            attributes["class"] = className;
        }

        var style = BuildStyle().Build();
        if (!string.IsNullOrWhiteSpace(style))
        {
            attributes["style"] = style;
        }

        if (!Visible)
        {
            attributes["hidden"] = true;
        }

        if (Disabled && SupportsDisabled)
        {
            attributes["disabled"] = true;
            attributes["aria-disabled"] = "true";
        }

        return attributes;
    }

    protected override void OnParametersSet()
    {
        base.OnParametersSet();

        if (Element.HasValue)
        {
            _externalElementProvided = true;
            SetRootElement(Element.Value);
        }
        else if (_externalElementProvided)
        {
            _externalElementProvided = false;
            ClearRootElement();
        }
    }

    protected sealed override void OnInitialized()
    {
        base.OnInitialized();

        if (HasJsModules && !_jsScanned)
        {
            JsModuleManager.ScanComponent(GetType());
            _jsScanned = true;
        }

        OnComponentInitialized();
    }

    /// <summary>
    /// Provides component-specific initialization without replacing the base lifecycle.
    /// </summary>
    protected virtual void OnComponentInitialized()
    {
    }

    protected sealed override async Task OnAfterRenderAsync(bool firstRender)
    {
        await base.OnAfterRenderAsync(firstRender);

        if (_rootElementChanged)
        {
            _rootElementChanged = false;
            if (ElementChanged.HasDelegate)
            {
                await ElementChanged.InvokeAsync(_rootElement);
            }
        }

        if (firstRender && HasJsModules)
        {
            await LoadJsModulesAsync();
        }

        await OnComponentAfterRenderAsync(firstRender);
    }

    /// <summary>
    /// Provides component-specific post-render logic after the optional JS module
    /// lifecycle has completed.
    /// </summary>
    protected virtual Task OnComponentAfterRenderAsync(bool firstRender) => Task.CompletedTask;

    /// <summary>
    /// Loads the JS modules declared by the component after its first render.
    /// </summary>
    protected virtual async Task LoadJsModulesAsync()
    {
        if (!HasJsModules)
        {
            return;
        }

        await JsModuleManager.LoadComponentAsync(GetType());
        _jsModuleLoaded = true;
        var interactiveModule = JsModules.SingleOrDefault(attribute => attribute.Interactive);

        if (interactiveModule is null)
        {
            return;
        }

        _dotNetReference ??= DotNetObjectReference.Create(this);
        await JsModuleManager.InitializeInteractiveAsync(
            interactiveModule.Name ?? interactiveModule.Path,
            _dotNetReference,
            InstanceId);
    }

    public async ValueTask DisposeAsync()
    {
        if (_disposed)
        {
            return;
        }

        _disposed = true;

        try
        {
            if (_jsModuleLoaded)
            {
                var module = JsModules.SingleOrDefault();
                if (module is not null)
                {
                    await JsModuleManager.DisposeModuleAsync(module.Name ?? module.Path, InstanceId);
                }
            }

            await OnComponentDisposeAsync();
        }
        finally
        {
            _dotNetReference?.Dispose();
            _dotNetReference = null;
            GC.SuppressFinalize(this);
        }
    }

    /// <summary>
    /// Provides component-specific asynchronous cleanup. The base class always
    /// releases its JS callback reference after this hook completes.
    /// </summary>
    protected virtual ValueTask OnComponentDisposeAsync() => ValueTask.CompletedTask;

    protected bool IsDisposed => _disposed;

    /// <summary>
    /// Updates the root element reference when a concrete component assigns its
    /// <c>@ref</c> value to <see cref="RootElement"/>.
    /// </summary>
    protected void SetRootElement(ElementReference element)
    {
        if (string.IsNullOrEmpty(element.Id))
        {
            return;
        }

        if (!_rootElementInitialized || !string.Equals(_rootElement.Id, element.Id, StringComparison.Ordinal))
        {
            _rootElement = element;
            _rootElementInitialized = true;
            _rootElementChanged = true;
        }
    }

    /// <summary>
    /// Clears the root element reference and schedules an ElementChanged
    /// notification with the default reference.
    /// </summary>
    protected void ClearRootElement()
    {
        if (!_rootElementInitialized)
        {
            return;
        }

        _rootElement = default;
        _rootElementInitialized = false;
        _rootElementChanged = true;
    }
}
